### ISSUE TITLE
Authentication not working.

### ISSUE THREAD

**Issue by Harsh3305** [Harsh3305/HRV-Mart#25]
https://github.com/nextauthjs/next-auth/issues/5743

**Comment by Harsh3305** [comment]
Change version of next-auth to 4.15.1.
⚠️ This is temporary solution.

**Comment by balazsorban44** [comment]
Hi there, there is a quick experimental version that addresses this, see https://github.com/nextauthjs/next-auth/issues/5743#issuecomment-1304860571 I plan to release it after some quick testing :soon:

**Comment by Harsh3305** [comment]
Resolved this issue in #30
